### ISSUE TITLE
better item type support for one handed mace / etc.

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#105]
Currently we analyze weapons in two different areas:

1. `attributes.equipType` indicates how the item is equipped for game mechanics, such as `One Handed Melee Weapon`
2. `properties.Weapon.type` contains a boolean attribute for various weapon types

Thus, if you wanted to find a One Handed Mace, you must search for items where `properties.Weapon.type.Mace = true` AND `attributes.equipType = One Handed Melee Weapon`

I propose adding a new field to item attributes specifically for Weapons named `attributes.weaponType` which will contain a more generic weapon type as used for gems/etc. In the example above, a one handed sceptre would have an `attributes.weaponType` set to `One Handed Mace` etc.

**Comment by trackpete** [comment]
Actually, not sure what I was thinking, looks like `properties.Weapon.type.X` field is always accurate. That said, since it's a field name, it's not as easily searchable in some situations.

Thus, if an item has that field set, I've extracted the field name and set it into `attributes.weaponType` - if an item has MULTIPLE of these set, it will grab a random one.

**Comment by thirdy** [comment]
Right now I do it these two fields:

attributes.itemType attributes.equipType
Both are string, equipType should be "One Handed Melee Weapon"
and itemType  should be Mace

maybe we have redundant fields already?

On Sun, Feb 28, 2016 at 12:16 PM, Pete Waterman <notifications@github.com>
wrote:

> Closed #105 <https://github.com/trackpete/exiletools-indexer/issues/105>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/105#event-569487001>
> .
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by trackpete** [comment]
Ah, yep, that works too. The main reason I added the new field was just to have a single selector for weapons instead of having to choose two - so you can have one automated dropdown for weapon type that shows all of the options, instead of having to select one handed vs two handed then the weapon type. 

For a hard coded backend it's not a big deal since you can pre-code a match against two fields, but adding that field allows dynamic population of a weapon type form that makes it easier.
