### ISSUE TITLE
Total DPS displaying incorrectly

### ISSUE THREAD

**Issue by kyri0** [trackpete/exiletools-indexer#114]
Heyo,

The total dps `properties.Weapon.Total DPS` doesn't display the estimated q20 total value, only for the actual quality. eg:
http://imgur.com/ikTbD3Q

Can you make it display the q20 total or better create a new one (like in pdps and q20pdps) for this purpose?

Cheers

**Comment by trackpete** [comment]
Yes, excellent point, I will add support for that.

**Comment by trackpete** [comment]
Okay, this is done and will show up as `propertiesPseudo.Weapon.estimatedQ20.Total DPS` when 3.1 is pushed into production.
