### ISSUE TITLE
Dynamically Add Player Ladder Info to Elastic JSON Results

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#116]
Rather than having a separate calls to the Ladder API, why not have a header flag to the Indexer API to add player's ladder info.

This api:

 > http://api.exiletools.com/ladder?league=all&accountName=watermnp:watermnp2:watermnp3

sounds inefficient and limited  accdg to the doc:

 > Returns all character information for accounts exactly matching the text. Up to 256 bulk account names may be specified if separated by a colon, though a performance penalty occurs.

And ofc, this would be very convenient to the client and also efficient since there's less http requests to make.

**Comment by trackpete** [comment]
It's way too heavy to do this constantly, we'd be searching and re-indexing hundreds of thousands of documents every couple of minutes (and it will only work for ladder players). For on-line stuff we just need to bug GGG to make their API public already.
