### ISSUE TITLE
Mappings should not contain new lines

### ISSUE THREAD

**Issue by flyweight** [trackpete/exiletools-indexer#119]
http://exiletools.com/info/mapping

Currently there is a mod "chance to Dodge Spell Damage" that contains a newline.  Each mapping should appear on its own line.

>enchantMods.40% increased Searing Bond Totem Placement Speed
enchantMods.5% chance to Dodge Spell Damage if you've
taken Spell Damage Recently
enchantMods.5% increased Discharge Radius
enchantMods.50% chance to Avoid being Stunned if you've Killed Recently
enchantMods.50% increased Rallying Cry Buff Effect
enchantMods.6% Chance to Dodge if you've taken a Critical Strike Recently
enchantMods.6% chance to Dodge Spell Damage if you've
taken Spell Damage Recently
enchantMods.6% chance to Freeze, Shock and Ignite if you haven't Crit Recently

**Comment by trackpete** [comment]
Dammit GGG:

```
          "enchantMods": [
            "5% chance to Dodge Spell Damage if you've\ntaken Spell Damage Recently"
          ],
```

Hah. I wondered if GGG was going to do that. So annoying.

Short term, I've modified the mapping endpoint tool to print the stupid newline character:

http://api.exiletools.com/endpoints/mapping?field=enchantMods

 I've also modified sub.formatJSON.pl to replace newlines with spaces in enchantMods names, however I will need to rebuild the index for this to take effect. Later in the week.

**Comment by flyweight** [comment]
Looks good.  Thanks.

**Comment by trackpete** [comment]
Note that to actually query ElasticSearch you'll need to use the exact `\n` not a newline, i.e.:

```
{
"query": {
"bool": {
  "must": [
    { 
      "term": {
        "enchantMods.5% chance to Dodge Spell Damage if you've\ntaken Spell Damage Recently": {
          "value": true
        }
      }
    }
  ]
}
},
size:500
}
```
