### ISSUE TITLE
Add a lookup reference index containing online players

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#124]
Based on this documentation:

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html

and this forum post:

https://discuss.elastic.co/t/array-size-inside-of-terms-query-cannot-exceed-1000-indices/12945

It should be possible to use a `terms lookup` for `shop.sellerAccount` against a large list of account names stored in a separate type/index. I think it's a good solution for filtering online only players and I have a gut feeling that this would be a good fit to the yet to be released GGG's player api.

I'd be glad to help out on implementing this in anyway I can.

**Comment by trackpete** [comment]
By my understanding, this isn't the way it's going to work.

From a previous comment:

```I would stick with filtering the results client side (not adjusting queries to the index) because that's how the official API will most likely work. You will request say 200 items then hit the official API to see which of those sellers are on-line and then filter the results to only display the 50 items from on-line sellers (and can perform a scroll or similar query to get more results, then filter those).```

The information I have on the official API is that it will work similar to the way the account status queries work on the exiletools ladder API. Breaking this down in more detail, here's how it should work with the ExileTools Index:

1. You perform a query against the ExileTools index and receive a list of matching items.
2. You parse this to create a list of `shop.sellerAccount` account names
3. You send this list as a query to GGG's On-line Status API
4. GGG's API returns that list telling you the on-line status for each account in that list
5. You filter the results to show only the items from the accounts which returned as on-line

You will NOT have access to a list of accounts that are on-line. You MUST give it an account name and ask if it's on-line. All of the processing of on-line/off-line will be client side, and the index will never reflect or include on-line status.

It's the same way it'd work doing it against the ExileTools Ladder API in list form:

1. Perform a query, get back items from `Deadmad` `magshen` and `xoffan`
2. Check their online status http://api.exiletools.com/ladder?league=perandus&accountName=Deadmad:magshen:xoffan
3. Filter results

Again, the index will never know and you'll never have a complete list of on-line players. GGG won't release that information for privacy reasons.

**Comment by thirdy** [comment]
> you'll never have a complete list of on-line players

But this can be achieved by simply querying GGG's api with all known account names.

There are 57,500 distinct account names right now in the item index. There might be some hard limits to how many account names you can request to the online-status api, but that can still be worked around.

I've only tried querying by pages atm and it's proving to be slow; tho I might just need to optimize. And using a scroll might be a lot better. In any case, filtering on the query to the item index would simplify a lot on the client side and save a lot of http requests.

_List all account names seen in the river in the past 30 days_
```
<!doctype html>
<html lang="en" ng-app="EsConnector">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Hello World Example w/ Angular</title>

  <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js"></script>
  <!-- Warning, I've seen some glitchy errors on newer versions, I think they require node.js installation or some idiocy -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/elasticsearch/10.0.1/elasticsearch.angular.min.js"></script>
  <script>
  
    // We define an EsConnector module that depends on the elasticsearch module.     
    var EsConnector = angular.module('EsConnector', ['elasticsearch']);

    // Create the es service from the esFactory
    EsConnector.service('es', function (esFactory) {
      return esFactory({ host: 'http://apikey:DEVELOPMENT-Indexer@api.exiletools.com' });
    });

    EsConnector.controller('ExileToolsHelloWorld', function($scope, es) {
      // Set up the ES Search function
      es.search({
          index: 'index',
              body: {
                  "aggs": {
                    "filtered": {
                      "filter" : { 
                                    "bool" : {
                                        "should" : [
                                            {
                                                "range" : {
                                                    "shop.updated" : {
                                                        "gte" : 'now-30d'
                                                    }
                                                }
                                            },
                                            {
                                                "range" : {
                                                    "shop.modified" : {
                                                        "gte" : 'now-30d'
                                                    }
                                                }
                                            },
                                            {
                                                "range" : {
                                                    "shop.added" : {
                                                        "gte" : 'now-30d'
                                                    }
                                                }
                                            }
                                        ]
                                    }
                                 },
                      "aggs": {
                        "sellers": {
                              "terms": {
                                "field": "shop.sellerAccount",
                                size:100000
                              }
                            }
                      }
                    }
                  },
                  "size": 0
              }
      }).then(function (response) {
        $scope.Response = response;
      }, function (err) {
        console.trace(err.message);
      });

    });
  
  </script> --

</head>
<body>
<!-- Main div starts at 0 spacing for simplicity -->
<div id="main" style="width:100%;padding-left:50px;padding-right:50px" ng-controller="ExileToolsHelloWorld" >
  <h1>This is a hello world test. You should see response data below. If not, check your console!</h1>
  <hr width=100% size=1>

  <div>
    <li>Request took {{Response.took}} ms
    <li>Request matched {{Response.hits.total}} hits
    <p>Here is some information on the items returned:</p>

    <ul>
      <!--li ng-repeat="(k,v) in Response">{{k}} - {{v | json}}</li-->
      <li ng-repeat="(k,v) in Response.aggregations.filtered.sellers.buckets">{{k}} - {{v | json}}</li>
    </ul>
  </div>
</div>
</body>
</html>
```

**Comment by trackpete** [comment]
I was told that brute force querying will get you banned. It's not the way
it's supposed to work. The way I described is the best way, and it's way
more efficient than trying to do a 50k term match. Don't do that. :p It is
really not optimized for that and you're forcing the queries to be insanely
heavy for no reason.

**Comment by trackpete** [comment]
Also we're never going to have the index updated by document based on
online status. That would require hundreds or thousands of additional
queries per second to keep them updated. The index isnt designed for that.
Storing online status in a second queryable database is the only way this
works at scale,so that second call will always be necessary.

**Comment by thirdy** [comment]
Ok thanks for explaining, good to know.
