### ISSUE TITLE
Physical life leech value has incorrect value

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#127]
For this mod `"#% of Physical Attack Damage Leeched as Life": 21`, 21 should be 0.21

See more here:
https://github.com/exiletrade/exiletrade/issues/61

**Comment by trackpete** [comment]
I'll look into this soon, can you check if poetrade has the same problem?
May be a raw data issue, there's no reason offhand I can think of for this
to happen, it's a direct copy of the variable from original data.

**Comment by thirdy** [comment]
Here's a copy paste from poe.trade:

maybe poe.trade is dividing it by 100?

31% increased Armour and Evasion P6
+35 to maximum Life P6
+38% to Fire Resistance S3
0.21% of Physical Attack Damage Leeched as Life P1


On Sat, Mar 26, 2016 at 8:54 AM, Pete Waterman <notifications@github.com>
wrote:

> I'll look into this soon, can you check if poetrade has the same problem?
> May be a raw data issue, there's no reason offhand I can think of for this
> to happen, it's a direct copy of the variable from original data.
> On Mar 25, 2016 8:24 PM, "thirdy" <notifications@github.com> wrote:
>
> > For this mod "#% of Physical Attack Damage Leeched as Life": 21, 21
> > should be 0.21
> >
> > See more here:
> > exiletrade/exiletrade#61
> > <https://github.com/exiletrade/exiletrade/issues/61>
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/trackpete/exiletools-indexer/issues/127>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/127#issuecomment-201626725>
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by Kubuxu** [comment]
I don't think it would solve the problem as sometimes the value will be: `3%` which is on real item `0.3%`.

**Comment by thirdy** [comment]
How about directly prepending with "0."

On Sat, Mar 26, 2016 at 4:04 PM, Jakub Sztandera <notifications@github.com>
wrote:

> I don't think it would solve the problem as sometimes the value will be:
> 3% which is on real item 0.3%.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/127#issuecomment-201729114>
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by Kubuxu** [comment]
Then again you have life leech gem which has `124%`.

**Comment by trackpete** [comment]
Okay, I found the problem. During the Ascendancy release I added code to remove periods from mod names, unfortunately this impacted the values of any number with a period. Ergh. I changed this to remove `.[space]` instead of just `.` and am deploying to production. Note, this will only fix NEW items coming in as stash tabs are updated.

**Comment by trackpete** [comment]
Confirmed, this is now fixed. New items in the stream are getting the values properly detected:

`"#% of Physical Damage Leeched as Life": 0.2,` etc.
