### ISSUE TITLE
v4 Pipeline Conversion

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#131]
v3 of the ExileTools Indexer uses linear processing to import data:

1. Fetch the latest changes from the Stash Tab API
2. Process the data
3. Convert the data to a better JSON format for ElasticSearch
4. Fetch historical data and merge information with converted new data
5. Submit data to ElasticSearch

While sections of this run in parallel forks to improve processing, the overall speed is limited by each linear step. For Version 4, the idea is to implement an asynchronous pipeline for data import. This idea is not fully fleshed out, so the first stage will be to do this, but for now here is an initial idea of how this pipeline might work:

1. Stash Tab API Consumer (Pipeline Producer):
  Dedicated process that only consumes the data from the Stash Tab API. Minimal/no processing will be performed on this data, instead it will be shoved directly into Kafka. 

2. Kafka:
  Two topics, one for new unformatted data and one for formatted data.

3. Formatting Consumer:
  The formatting consumer will note changes in the message queue and convert the original Stash Tab API GGG JSON into PWX formatted JSON data, pushing this into a new topic.

4. ES Import Consumer:
  The ES Import Consumer will take PWX formatted JSON data and import this into ElasticSearch.

5. Live Monitor Consumer:
  The Live Monitor Consumer will be designed to search for specific attributes in the PWX formatted JSON data and trigger events based on matches. This could be sending data over a web socket or configured push events, for example. This part will be developed separately.

The end goals of this pipeline conversion will be:

1. De-couple downloading of data, processing of data, and importing of data into ES, so that all of these tasks can be performed asynchronously and continuously. New data will be processed while other stash tab data is downloaded while other processed data is bulk imported into ES.

2. Remove the need for manual forking of processing tasks. Instead, have X active consumers watching the message queue and waiting to jump on data as it comes available.

3. Provide a system to re-import historical data with new processing with minimal overhead.

**Comment by trackpete** [comment]
In the first round of re-factoring for this, I created a new branch called `v4kafka` assuming I will be doing some testing with Apache Kafka.

The first modifications necessary were to re-design parts of the `poe-watch-stash-tab-river.pl` script to only consume updates from the Stash Tab API. The only processing done on this data after loading into memory is to split up the array of stash tabs, because each stash tab will eventually be directly inserted into a Kafka topic (or similar) for processing by another system.

The main processing question here is **what should I store in Kafka?** Each stash tab is referenced in memory as a perl hash, but that perl hash needs to be put into some sort of storable format to go into Kafka. There's a surprising amount of overhead here.

To perform this testing, I deployed a new small virtual machine so that the testing wouldn't be unfairly influenced by active processing on one of my main nodes. I then added support to `poe-watch-stash-tab-river.pl` to source data directly from the flat files I have stored of historical river data, choosing a random date of `20160312`. This way I can repeatably scan and prepare the exact same JSON data structures for storage.

The following are some benchmarks from processing 50 updates:

* No Storing: 50 processed in 0.00278199999999997
* JSON::XS->New: 50 processed in 1.13069 seconds
* JSON::XS via encode_json: 50 processed in 1.17653
* Data::Dumper: 50 processed in 18.104544 seconds
* Storable->nfreeze: 50 processed in 1.968698 seconds

JSON::XS pretty much dominates, so it looks like that's the format we'll use for storing each stash tab in the queue system.

**Comment by trackpete** [comment]
Producing messages into Kafka is extremely fast. Without any tuning, pushing the first 50 stash tab API updates (same as analyzed above) was done in ~7 seconds:

* 50 processed in 7.657006 seconds (0.15314012 sec / update)

This is with one partition and one broker with a replication factor of 1. So pushing this data into kafka increased base processing overhead of 50 updates from 1.1s to 7.6s, which is certainly acceptable (again without any tuning).

**Comment by trackpete** [comment]
Consumption from kafka is very fast as well (note that I'm probably limited by NFS on this filesystem). I loaded a few thousand stash tabs into kafka then benchmarked simply consuming all of them while decoding the JSON for each one:

* Fri Apr  8 19:20:19 2016 Consumed 36539 stashtabs in 23.823031 seconds (1533.76789040824 tab/s).

Adding in additional processing where each item in a stash tab is looped through slows things down a bit in single thread processing:

* Fri Apr  8 20:43:21 2016 Consumed 29960 stashtabs (1083248 items) in 23.302803 seconds (1285.68224174577 tab/s, 46485.7382178444 items/s).

(note I switched to slightly different data in the middle of this, genius right?)

Distressingly, I noticed that when adding my `&formatJSON` subroutine call into this, the processing performance drops by orders of magnitude:

* Fri Apr  8 20:45:26 2016 Consumed 640 stashtabs (24118 items) in 49.183966 seconds (13.0123707388705 tab/s, 490.363058562622 items/s).

This honestly makes me concerned that the problem may actually be something in the complexity of that subroutine. It shouldn't cause things to be 10x slower. Time to do more analysis in that subroutine.

**Comment by trackpete** [comment]
After doing some more reading into this, I decided to look into experimenting with BerkeleyDB as the per-get/set statistics for Perl are apparently quite fast (thanks to no overhead of IPC/TCP/etc. calls). I did an initial conversion of loading all of the item data into a BerkeleyDB file then performed some initial testing. Holy smokes!

Single instance performance, *per item*:

* 65.1456787668584 tab/s, 2436.54861000169 items/s

This is vs a ~20GB DB file (on SSD) with ~25mil items. Crazy fast! Comparatively here is an ElasticSearch comparison *per stash tab* on the new node:

* 30.9656813827877 tab/s, 1162.00126919883 items/s

Nearly double the performance! The next question is - does it scale? Let's check processing speed with eight parallel consumers for BerkeleyDB:

* 43.8869674274304 tab/s, 1635.36344316891 items/s

A small hit but not much! That means we're processing about ~300 stashes per second! With no extra load on ES. I think BerkeleyDB is where we're going.

**Comment by trackpete** [comment]
I've added the "processed" topic to kafka and performed some performance testing of the pipeline up to (but not including) bulk indexing the final data into Elasticsearch.

* 1 consumer eating API data and writing to 8 incoming partitions
* 8 consumers eating Stash API data, converting to ES JSON, and writing to 1 processed partition

During performance testing, I'm reading incoming API data without sleeps directly from files. This is consuming data at a rate that is exponentially faster than the web API. For example:

```
Mon Apr 25 16:18:19 2016 . [2206412-2329581-2174147-2554390-2427879] Downloaded 0.00MB of compressed JSON (0.00MB raw) in 0.053556 seconds (0.00KB/s)
Mon Apr 25 16:18:20 2016 . [2206412-2329581-2174147-2554390-2427879] Added 58 stashes to Kafka and indexed stats for 1461615499sqjej to Elasticsearch in 0.207925 seconds
Mon Apr 25 16:18:21 2016 $ Full update consumed in 1.290753 seconds
Mon Apr 25 16:18:21 2016 . [2206417-2329598-2174159-2554407-2427888] Downloaded 0.00MB of compressed JSON (0.00MB raw) in 0.046787 seconds (0.00KB/s)
Mon Apr 25 16:18:21 2016 . [2206417-2329598-2174159-2554407-2427888] Added 60 stashes to Kafka and indexed stats for 1461615501rtcfo to Elasticsearch in 0.202446 seconds
Mon Apr 25 16:18:22 2016 $ Full update consumed in 1.275814 seconds
Mon Apr 25 16:18:22 2016 . [2206428-2329611-2174171-2554419-2427902] Downloaded 0.00MB of compressed JSON (0.00MB raw) in 0.037548 seconds (0.00KB/s)
Mon Apr 25 16:18:22 2016 . [2206428-2329611-2174171-2554419-2427902] Added 52 stashes to Kafka and indexed stats for 1461615502uiftx to Elasticsearch in 0.234775 seconds
Mon Apr 25 16:18:23 2016 $ Full update consumed in 1.304638 seconds
Mon Apr 25 16:18:23 2016 . [2206438-2329624-2174185-2554431-2427907] Downloaded 0.00MB of compressed JSON (0.00MB raw) in 0.063834 seconds (0.00KB/s)
Mon Apr 25 16:18:23 2016 . [2206438-2329624-2174185-2554431-2427907] Added 53 stashes to Kafka and indexed stats for 1461615503ltbgj to Elasticsearch in 0.200321 seconds
Mon Apr 25 16:18:24 2016 $ Full update consumed in 1.292219 seconds
Mon Apr 25 16:18:24 2016 . [2206443-2329638-2174196-2554440-2427923] Downloaded 0.00MB of compressed JSON (0.00MB raw) in 0.043487 seconds (0.00KB/s)
Mon Apr 25 16:18:25 2016 . [2206443-2329638-2174196-2554440-2427923] Added 69 stashes to Kafka and indexed stats for 1461615504rzotw to Elasticsearch in 0.213857 seconds
Mon Apr 25 16:18:26 2016 $ Full update consumed in 1.290549 seconds
```

With 8 consumers of this data, they are *easily* parsing faster than the incoming topic can be populated, example from one of the consumers:

```
Mon Apr 25 16:18:20 2016 * Consumed 9 stashtabs (204 items) in 0.15s (60.60 tab/s, 1373.68 items/s) (0.02s kafka production time).
Mon Apr 25 16:18:20 2016 ? Loaded incoming payload from Kafka from offset 4815 in 0.000992 seconds
Mon Apr 25 16:18:20 2016 * Consumed 1 stashtabs (43 items) in 0.03s (35.44 tab/s, 1523.90 items/s) (0.00s kafka production time).
Mon Apr 25 16:18:20 2016 ! No additional messages consumed from partition 2 offset 4816, sleeping for 1s and re-trying.
Mon Apr 25 16:18:21 2016 ! No additional messages consumed from partition 2 offset 4816, sleeping for 1s and re-trying.
Mon Apr 25 16:18:22 2016 ? Loaded incoming payload from Kafka from offset 4816 in 0.002448 seconds
Mon Apr 25 16:18:22 2016 * Consumed 10 stashtabs (405 items) in 0.34s (29.50 tab/s, 1194.63 items/s) (0.02s kafka production time).
Mon Apr 25 16:18:22 2016 ? Loaded incoming payload from Kafka from offset 4826 in 0.001387 seconds
Mon Apr 25 16:18:22 2016 * Consumed 4 stashtabs (169 items) in 0.10s (39.47 tab/s, 1667.80 items/s) (0.01s kafka production time).
Mon Apr 25 16:18:22 2016 ? Loaded incoming payload from Kafka from offset 4830 in 0.001704 seconds
Mon Apr 25 16:18:22 2016 * Consumed 3 stashtabs (211 items) in 0.13s (23.35 tab/s, 1642.20 items/s) (0.01s kafka production time).
Mon Apr 25 16:18:22 2016 ! No additional messages consumed from partition 2 offset 4833, sleeping for 1s and re-trying.
Mon Apr 25 16:18:23 2016 ! No additional messages consumed from partition 2 offset 4833, sleeping for 1s and re-trying.
```

For additional analysis, I consumed directly from the official API, early in the stream where updates have lots of stash tabs. Notice how much longer it takes to download and process this data:

```
Mon Apr 25 16:20:04 2016 ! Processing API URL: http://www.pathofexile.com/api/public-stash-tabs
Mon Apr 25 16:20:07 2016 . [0] Downloaded 1.04MB of compressed JSON (4.97MB raw) in 3.864401 seconds (274.96KB/s)
Mon Apr 25 16:20:08 2016 . [0] Added 294 stashes to Kafka and indexed stats for 1461615604gzagb to Elasticsearch in 0.384983 seconds
Mon Apr 25 16:20:09 2016 $ Full update consumed in 5.302462 seconds
Mon Apr 25 16:20:09 2016 ! Processing API URL: http://www.pathofexile.com/api/public-stash-tabs?id=220-2017-804-1343-262
Mon Apr 25 16:20:13 2016 . [220-2017-804-1343-262] Downloaded 1.05MB of compressed JSON (5.11MB raw) in 4.248402 seconds (251.91KB/s)
Mon Apr 25 16:20:14 2016 . [220-2017-804-1343-262] Added 318 stashes to Kafka and indexed stats for 1461615609rswok to Elasticsearch in 0.501688 seconds
Mon Apr 25 16:20:15 2016 $ Full update consumed in 5.814853 seconds
Mon Apr 25 16:20:15 2016 ! Processing API URL: http://www.pathofexile.com/api/public-stash-tabs?id=482-3227-1842-2736-1129
Mon Apr 25 16:20:19 2016 . [482-3227-1842-2736-1129] Downloaded 1.13MB of compressed JSON (5.28MB raw) in 4.170839 seconds (277.16KB/s)
Mon Apr 25 16:20:19 2016 . [482-3227-1842-2736-1129] Added 273 stashes to Kafka and indexed stats for 1461615615vtbyo to Elasticsearch in 0.483125 seconds
Mon Apr 25 16:20:20 2016 $ Full update consumed in 5.721803 seconds
Mon Apr 25 16:20:20 2016 ! Processing API URL: http://www.pathofexile.com/api/public-stash-tabs?id=693-4472-2902-3850-1719
Mon Apr 25 16:20:38 2016 . [693-4472-2902-3850-1719] Downloaded 0.57MB of compressed JSON (2.71MB raw) in 17.284111 seconds (33.51KB/s)
Mon Apr 25 16:20:38 2016 . [693-4472-2902-3850-1719] Added 180 stashes to Kafka and indexed stats for 1461615620czdbu to Elasticsearch in 0.317988 seconds
Mon Apr 25 16:20:39 2016 $ Full update consumed in 18.638173 seconds
```

The server on GGG's side is by far the limit here, with large updates taking many seconds to download. With 8 consumers on the client side we are absolutely crushing this data:

```
Mon Apr 25 16:21:48 2016 ? Loaded incoming payload from Kafka from offset 5328 in 0.003402 seconds
Mon Apr 25 16:21:49 2016 * Consumed 45 stashtabs (250 items) in 0.21s (215.70 tab/s, 1198.33 items/s) (0.04s kafka production time).
Mon Apr 25 16:21:49 2016 ! No additional messages consumed from partition 2 offset 5373, sleeping for 1s and re-trying.
Mon Apr 25 16:21:50 2016 ! No additional messages consumed from partition 2 offset 5373, sleeping for 1s and re-trying.
Mon Apr 25 16:21:51 2016 ! No additional messages consumed from partition 2 offset 5373, sleeping for 1s and re-trying.
Mon Apr 25 16:21:52 2016 ! No additional messages consumed from partition 2 offset 5373, sleeping for 1s and re-trying.
Mon Apr 25 16:21:53 2016 ! No additional messages consumed from partition 2 offset 5373, sleeping for 1s and re-trying.
Mon Apr 25 16:21:54 2016 ? Loaded incoming payload from Kafka from offset 5373 in 0.003979 seconds
Mon Apr 25 16:21:54 2016 * Consumed 35 stashtabs (743 items) in 0.50s (69.39 tab/s, 1473.08 items/s) (0.05s kafka production time).
Mon Apr 25 16:21:54 2016 ! No additional messages consumed from partition 2 offset 5408, sleeping for 1s and re-trying.
```

At this point we're actually **finished processing Update 1 server-side before Update 2 finishes downloading from GGG.**

That's pretty f'ing boss. To reduce complication a bit, I'm going to test this with fewer partitions.

**Comment by trackpete** [comment]
With 4 consumers:

1. Started parsing API data from files at 16:29:57
2. Started 4 consumers at 16:32:34
3. Consumers caught up to incoming stream at 16:33:42

With only 4 consumers we're still spending a fair amount of time waiting on payloads, and that's with a file source. Using API source they are spending a TON of time in wait, easily 75-80%.

**Comment by trackpete** [comment]
With a ton of other testing I haven't documented here, I've gone back on a lot of the more complex changes. Specifically, using an external DB to track items/stashes didn't work because it made it much harder to determine which items were removed from a stash tab.

As a result, the new pipeline that will be moving forward to production is as follows:

1. Get items from Stash Tab API, put into Kafka
2. Read items from Kafka, process them, bulk index into ElasticSearch. Send a copy to Kafka.

The first will run in a single threaded process writing to four kafka partitions, while the second will run with four threads doing the processing. Performance on the index is enough to "beat" incoming stream data in testing. 

The reason we write out the processed data to a single Kafka partition is to potentially allow something else to consume that stream, such as live filtering. Whether or not I'll implement something for this is TBD.

**Comment by thirdy** [comment]
Sounds great. I am certainly interested on making a Kafka client subscriber
