### ISSUE TITLE
v4 test redis for intermediary item status store

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#133]
With the latest improvements, the biggest bottleneck to processing incoming items is now the historical item lookup by a huge margin. This costs ~2-50ms per stash tab and adds up very fast, effectively limiting the pipeline from ~4000 items/s to ~1000 items/s and even less when multi-threaded.

To see if we can speed this up, let's experiment with using a separate redis store to only maintain items and their previous status (added, modified, etc.). Hopefully this will allow scaling up of the pipeline speed.

**Comment by trackpete** [comment]
I have redis up and running and created a new script in tools called `temp-esdata-to-redis.pl` which will bulk transfer shop history fields into redis. This script will be needed in the production deployment of v4 in order to populate the redis "cache" for shop data.

It takes a bit of time to run, limited by the speed of elasticsearch I expect. At this time, I started an import run at `Apr 16 18:21:51` and will track it for the duration (currently it has processed 3.4mil items in 20min, which means a couple of hours for the entire 22mil index).

Once that's complete, I'll do some testing with processing speed pulling data from redis.

note: Initially I'm storing keys in redis for each item based on it's uuid. In Elasticsearch this would be prohibitively slow as it would require thousands of searches per second. I'm hoping redis will be faster. If this turns out to not be the case, I'll need to store data in redis based on the stashID and that will change things up a bit and be less cool (but faster, as you only need one query every X number of items instead of every item).

**Comment by trackpete** [comment]
Here are some general redis stats at the current testing phase.

First, here is a baseline without elastic or redis item history lookup with current processing stuff:

* (69.9179931857924 tab/s, 2524.13943685451 items/s)

Here is the next offset processed with JSON encoding of a redis cache per item:

* (61.8277829502116 tab/s, 2213.16965340493 items/s)

Here is the next offset processed fetching the redis cache for every item and processing it:

* (44.6366171259732 tab/s, 1590.08383521895 items/s)

Here is the next offset processed also adding each item back into redis:

* (40.473018755446 tab/s, 1463.13076110072 items/s)

Now, comparatively, here is the next offset processed querying history via stashtab from ElasticSearch:

* (15.6986413453861 tab/s, 567.687022805078 items/s)

**Good:** Using a per-item redis cache speeds things up by ~300% over fetching per-stash data from ElasticSearch.

**Bad:** Using a per-item redis cache still slows things down a fair bit. Also, this current implementation does not include per-stash tracking (i.e. for GONE items), which will require a separate redis DB. Also, the current Redis cache is using almost 10GB of memory for 22mil items. That's a lot.

**Next Steps:** Clear out the redis db and modify temp-esdata-to-redis.pl with an alternate subroutine to bulk load entire stash tabs of information into redis, and try running redis with per-stash-tab data. Also, compare overall data size.

**Comment by trackpete** [comment]
Just to add to this before moving on to next steps, I did some parallel testing. With 8 threads reading from kafka partitions, the overall speed was about the same.

Average with elastic search was around 450 items/second on each thread running at the same time.

Interestingly, the average performance with redis dropped significantly - down to an average of about 600 items/s with 8 threads in parallel. This is very disappointed, but **may** be due to the huge overhead of getting/setting for each item. I think it's still worth analyzing performance at a per-Stash get/set level.

**Comment by trackpete** [comment]
I also did some testing on an SSD backed node with Elasticsearch and was easily update to sustain 8x~1100 items/s query processing. That's fast enough that it will probably be easier and better to go ahead and upgrade the infrastructure for these systems to SSD's, which will also improve general query/index performance and skip Redis entirely.

In the short term I think I'll just stick with the current pipeline enhancement using ES and skip the intermediate Redis database.

**Comment by thirdy** [comment]
Look forward for this improvement. Last time I checked, there's
considerable lag when I posted a Tabula for 1ch and showing up on
ExileTrade. And in that time, I've gotten so many whispers :D
