### ISSUE TITLE
sockets.largestLinkGroup

### ISSUE THREAD

**Issue by eveneveneven** [trackpete/exiletools-indexer#138]
When filtering items by sockets.largestLinkGroup it won't return items that don't exist with the specified number of links.

I expect some helmets to match this filter since they exist with 1-4 links which matches "<= 5". But they won't since they can't have 5 links. Not sure if this is intended.

Example:

`"query": {
    "filtered": {
      "filter": {
        "bool": {
         "must": [
            { "term": { "attributes.rarity": "Unique" } },
            { "term": { "attributes.league": "$scope.league" } },
            { "term": { "info.fullName": "$scope.unique" } },
            { "term": { "sockets.largestLinkGroup": "5" } },
            { "term": { "shop.verified": "GONE" } },
            { "range": { "shop.chaosEquiv": { "gt": 0 } } }`

**Comment by eveneveneven** [comment]
Basically what I want to do is search for any unique and exclude 6L, and maybe 5L and return price stats.

**Comment by trackpete** [comment]
`largestLinkGroup` is a literal match showing the largest link group that the item actually has. By doing a term match against `largestLinkGroup:5` you're actually asking it to show you all 5L items.

If you want to exclude 6L and/or 5L items, you should instead do a range match against `largestLinkGroup` such as `"range": { "sockets.largestLinkGroup" : { "lt" : 6 } }` etc. Does that make sense?

**Comment by trackpete** [comment]
Also, I don't think it makes much of a difference in the grand scheme of things, but instead of searching for `shop.chaosEquiv gt 0` you can just search for `shop.hasPrice = true` (this comes in handy if you're doing two way data binding).

**Comment by eveneveneven** [comment]
Yeah that makes sense. Thanks for answering and clearing that up. I'm reading up on the range filter now :-)

What I ended up doing was using `"range": { "sockets.largestLinkGroup" : { "lte" : 4 } }` on body armor, bows and two handed melee weapons. With the exception of Kaom's and Tabula Rasa.

**Comment by trackpete** [comment]
Perfect!
