### ISSUE TITLE
ElasticSearch mappings throwing error

### ISSUE THREAD

**Issue by flyweight** [trackpete/exiletools-indexer#148]
http://api.exiletools.com/endpoints/mapping
```
<h1>Software error:</h1>
<pre>An error happened: Host http://elasticsearch:9200/poe/item/_mapping Couldn't connect to server (7)
 at /var/www/cgi-bin/api-endpoints/indexer-mapping.pl line 36.
</pre>
<p>
For help, please send mail to the webmaster (<a href="mailto:pete@pwx.me">pete@pwx.me</a>), giving this error message 
and the time and date of the error.

</p>
```

**Comment by trackpete** [comment]
Woops. I forgot to update these scripts to point at the new elasticsearch index. This is done now. Thanks for the reminder/heads up!

**Comment by flyweight** [comment]
Still not working for me.  Frontend cache needs to be cleared?

**Comment by trackpete** [comment]
Yep, sorry, forgot those endpoints have a longer than normal cache time. Looks good externally for me now.

**Comment by flyweight** [comment]
Working for me.  Thanks :)
