### ISSUE TITLE
Store pricing/sale type (b/o, price, etc.) in Database and process into ElasticSearch

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#39]
We detect the "type" of currency pricing (b/o, price, c/o) but do not store it. It's sent to ProcessItemFragment as "$type":

```  my $type = $_[1]; ```

However beginning on 337 we don't insert that into the database.

The table itself also needs to have this row added.

Let's add this as "saleType" to the database and "shop.saleType" to ES.

**Comment by trackpete** [comment]
Added "saleType" column as varchar(16) to indexer.items table in MariaDB

**Comment by trackpete** [comment]
* Set $type to "offer" if it's not defined.
* Added saleType to insert/update code
* updated format-and-load-db-to-es.pl to handle the 13th column as $saleType
* updated format-and-load-db-to-es.pl to formation this as shop.saleType

**Comment by trackpete** [comment]
Updated setup/database-indexer-tables.sql

**Comment by trackpete** [comment]
Added ability to re-run load-data-from-disk using `-after <timestamp>` to flush some new saleTypes into the database.

**Comment by trackpete** [comment]
```
MariaDB [indexer]> select count(`saleType`) as count, `saleType` from `items` group by `saleType`;
+-------+----------+
| count | saleType |
+-------+----------+
|     0 | NULL     |
| 25154 | b/o      |
|     4 | c/o      |
|  2254 | offer    |
|  1872 | price    |
+-------+----------+
5 rows in set (2.12 sec)
```
Some data shoved into the database now and it looks like this information is being stored.

**Comment by trackpete** [comment]
And they're in ES!

```
{
"aggs": {
  "saletype": {
    "terms": {
      "field": "shop.saleType"
    }
  }
},
size:0
}

{
  "took": 200,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 5668836,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "saletype": {
      "doc_count_error_upper_bound": 0,
      "sum_other_doc_count": 0,
      "buckets": [
        {
          "key": "b/o",
          "doc_count": 25057
        },
        {
          "key": "offer",
          "doc_count": 2252
        },
        {
          "key": "price",
          "doc_count": 1862
        },
        {
          "key": "c/o",
          "doc_count": 4
        }
      ]
    }
  }
}

**Comment by thirdy** [comment]
how about those without any price/buyout etc., what is the shop.saleType
for those?

On Wed, Dec 2, 2015 at 5:19 AM, Pete Waterman <notifications@github.com>
wrote:

> And they're in ES!
>
> {
> "aggs": {
>   "saletype": {
>     "terms": {
>       "field": "shop.saleType"
>     }
>   }
> },
> size:0
> }
>
> {
>   "took": 200,
>   "timed_out": false,
>   "_shards": {
>     "total": 5,
>     "successful": 5,
>     "failed": 0
>   },
>   "hits": {
>     "total": 5668836,
>     "max_score": 0,
>     "hits": []
>   },
>   "aggregations": {
>     "saletype": {
>       "doc_count_error_upper_bound": 0,
>       "sum_other_doc_count": 0,
>       "buckets": [
>         {
>           "key": "b/o",
>           "doc_count": 25057
>         },
>         {
>           "key": "offer",
>           "doc_count": 2252
>         },
>         {
>           "key": "price",
>           "doc_count": 1862
>         },
>         {
>           "key": "c/o",
>           "doc_count": 4
>         }
>       ]
>     }
>   }
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/39#issuecomment-161098784>
> .
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by trackpete** [comment]
They should have a `shop.saleType` of `offer` if it's unknown. I've been working on adding details like this to the mapping information page (still a work in progress):

http://api.exiletools.com/info/indexer-docs.html

![image](https://cloud.githubusercontent.com/assets/8779751/11850494/9db1279e-a3fb-11e5-8330-6d909c574e8e.png)
