### ISSUE TITLE
Document the mapping in additional detail

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#42]
The mapping information for the JSON structure at http://api.exiletools.com/info/indexer.html is very sparse.

At the very least, any extracted mapping should be documented and everything but the specific mods/etc. should be documented. Explanations should be given for how the mods are created/etc.

**Comment by trackpete** [comment]
I have added a new informational page about this and am in the process of fleshing it out:

http://exiletools.com/info/indexer-docs.html

**Comment by thirdy** [comment]
(y), bookmarked. the examples would surely help newcomers. I'm sure more examples would be even greater. But ofc, it requires effort to write it.

**Comment by trackpete** [comment]
I've completed the documentation of the current mapping at this page:

http://exiletools.com/info/indexer-docs.html

Next up will be another page with more examples. Note that I also added a simple web script which generates very simple text output to visualize the mapping:

http://exiletools.com/info/mapping

Specific fields can be specified, such as:

http://exiletools.com/info/mapping?field=mods.Amulet.explicit
