### ISSUE TITLE
Request to format http://exiletools.com/status as JSON

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#47]
Hi Pete,

Requesting for a JSON format for:

[http://exiletools.com/status ](http://exiletools.com/status)

Example (it's missing other info, but those can be added too, the better):

```
[	
	{
		ladder : "darkshrine",
		indexer : "Darkshrine (IC003)",
		forum : "http://www.pathofexile.com/forum/view-forum/597/page"
	}, {
		ladder : "darkshrinehc",
		indexer : "Darkshrine HC (IC004)",
		forum : "http://www.pathofexile.com/forum/view-forum/598/page"
	}, {
		ladder : "hardcore",
		indexer : "Hardcore",
		forum : "http://www.pathofexile.com/forum/view-forum/305/page"
	}, {
		ladder : "standard",
		indexer : "Standard",
		forum : "http://www.pathofexile.com/forum/view-forum/306/page"
	}
]

```

Thanks!

**Comment by trackpete** [comment]
Yes, this is a great idea.

I also need to add support for checking the current status in Jenkins as well as the success/fail of the last run.

**Comment by trackpete** [comment]
Jenkins API: https://wiki.jenkins-ci.org/display/JENKINS/Remote+access+API

Tasks:

1. Ensure the Ladder API system and the Indexer both use the same `league-list` table.

2. Pull current active leagues from `league-list`

3. Pull current job enabled/disabled from jenkins api at `/api/json?pretty=true`

4. Pull most recent job status from jenkins api:

  Refresh Threads: /job/POE%20Index%20Refresh%20Shop%20Threads/lastBuild/api/json

  Index Forum: /job/POE%20Index%20Shop%20Threads/lastBuild/api/json

  Ladder: /job/POE%20Ladder%20Update/lastBuild/api/json

5. Pull statistics on the latest normal run for each forum. Elastic Search query via the `indexing-stats/run` index/type:

```
{
  "query": {
    "filtered": {
      "query": {
        "term": {
          "RunType": {
            "value": "normal"
          }
        }
      },
      "filter": {
        "term": {
          "Forum": "standard"
        }
      }
    }
  },
  "sort": [
    {
      "RunTimestamp": {
        "order": "desc"
      }
    }
  ],
  "size": 1
}
```

**Comment by trackpete** [comment]
(1) is complete.

**Comment by trackpete** [comment]
(3) and (4) are complete.

**Comment by trackpete** [comment]
(2) is complete. I've decided to skip (5) as that should be part of a different reporting bit (like the dashboard) and can easily be done remotely.

**Comment by trackpete** [comment]
http://exiletools.com/status will now only return data in JSON format. http://exiletools.com/status?pretty will pretty print the JSON output.

The data objects are as follows:

`Active Leagues` : Contains a data object for each currently active league according to `league-list`, including information on the start time, end time, shop forum id, the API name for the ladder (URI encoded), the league name in item json, and a pretty name. The root of each league object is named after the exiletools internal name, which can be used to query the ladder and the price macro/etc.

`Jobs` : Contains data objects with status on the jobs in Jenkins. There are two main objects, `Indexer` and `Ladder`. The important thing here is `Status` which will show either `enabled` or `disabled` - if a job is temporarily disabled for upgrades/maintenance/etc. that status is good to know. The other data is straight from jenkins as follows:

* If `Running` is `true` then it contains current run data. Some items like `Job Duration` may be 0, as that data is not stored until the job is completely.

* If `Running` is `false` the `Result` and all data will reflect the stats from the *last job run.* 

Note: The `Job Time` is in epoch milliseconds while the `Job Duration` is in seconds.

**Comment by trackpete** [comment]
One quick change:

By default it will now pretty print for legibility. If you want minimized JSON data back, just give it ?min i.e. http://exiletools.com/status?min

**Comment by thirdy** [comment]
Interesting to see that you have two jobs:

 1. Index Bumped Shop Threads 
 1. Refresh Shop Threads

Questions:
 
 1. Which of those are being used in http://exiletools.com/last-index-update.html
 2. How many shop threads are being scrapped by "Refresh Shop Threads" for one successful jenkins run?

(is it okay for me to ask questions here?)

**Comment by trackpete** [comment]
Totally okay to ask questions here, that helps keep it public for anyone else that is developing stuff.

Q1: last-index-update.html is updated only by the regular get-forum-updates.pl which runs every 12 minutes looking for bumped and new threads. 

Q2: The refresh runs vary significantly based on time of day and original index. They currently run every hour and look for up to 5,000 threads that have not been updated in the last 6 hours (this will get changed back to 12-24 soon because there are too many threads in Talisman). 

Refresh runs are logged in the stats index as type `run` with the `RunType` attribute of `refresh`:

http://exiletools.com/stats/run/_search

This query will show the last 100 refresh runs:

```
{
  "query": {
    "filtered": {
      "filter": {
        "bool": {
          "must" : [
            { "term" : { "RunType" : "refresh" }  }
            ]
        }
      }
    }
  },
  "sort": [
    {
      "RunTimestamp": {
        "order": "desc"
      }
    }
  ]
},
size:100
}
```

(RunType of "normal" is a check for bumped/new threads)

You can see more examples of using the stats index by checking out the javascript at http://exiletools.com/dashboard/ or https://github.com/trackpete/exiletools-reporting

Cheers!

**Comment by trackpete** [comment]
Oh, I should clarify:

The information in the `stats` index is **per job fork!** The stats refresh is currently run with 7 forks, so when you see 7 jobs with very close RunTimestamp that each fetched ~280 threads, that means the last update ran 280*7 = ~2000 threads.
