### ISSUE TITLE
Create an API front end to call verify-threads

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#63]
Create an API front end to allow third parties to make call to verify items and threads. Unlike poe.trade, this should work by requesting a verification update via the back end (this should be sustainable with low usage, in the long run something else may have to be done).

Triggering the verification call should result in the following:

1. Thread updated from the forum
2. Thread information updated in DB
3. Thread information pushed to ElasticSearch
4. Return response data for the specified items

The request should work by sending a comma separated list of item `uuids` to the verification engine (to begin with, perhaps a maximum of 10?). For example:

`/verify?items=1004841:0112ec9d4c1f24cfed80a5bee9434879,	995398:fe6353e080d932cfc70cecd6e1f1b0e5`

The backend should then update those threads and check the current status of the items when completed, then return this information in JSON data, such as:

```
{
  "Status" : {
    "1004841:0112ec9d4c1f24cfed80a5bee9434879" : {
      "verified" : YES,
      "currency" : "Exalted Orb",
      "amount" : 1,
      "modified" : 1234567,
      "updated" : 23454678
    },{
    "995398:fe6353e080d932cfc70cecd6e1f1b0e5" : {
      "verified" : NO,
      "currency" : "Exalted Orb",
      "amount" : 1,
      "modified" : 1234567,
      "updated" : 23454678
    }
  }
}
```

Prior to executing the verification update, it should also check to see when the thread was last updated - if the thread was updated within the last *Time Period* (60s?) do not trigger an update.

**Comment by thirdy** [comment]
Can we use this mechanic to trigger indexing of outdated (usually unbumped)
threads? But sounds like expensive but hopefully maybe not too expensive.
But there's still the problem of new items not indexed when you're
searching..

Side question: would it help if indexing was focued the temp leagues only?

On Tue, Dec 29, 2015 at 2:34 AM, Pete Waterman <notifications@github.com>
wrote:

> Create an API front end to allow third parties to make call to verify
> items and threads Unlike poetrade, this should work by requesting a
> verification update via the back end (this should be sustainable with low
> usage, in the long run something else may have to be done)
>
> Triggering the verification call should result in the following:
>
> 1 Thread updated from the forum
> 2 Thread information updated in DB
> 3 Thread information pushed to ElasticSearch
> 4 Return response data for the specified items
>
> The request should work by sending a comma separated list of item uuids
> to the verification engine (to begin with, perhaps a maximum of 10?) For
> example:
>
> /verify?items=1004841:0112ec9d4c1f24cfed80a5bee9434879,
> 995398:fe6353e080d932cfc70cecd6e1f1b0e5
>
> The backend should then update those threads and check the current status
> of the items when completed, then return this information in JSON data,
> such as:
>
> {
>   "Status" : {
>     "1004841:0112ec9d4c1f24cfed80a5bee9434879" : {
>       "verified" : YES,
>       "currency" : "Exalted Orb",
>       "amount" : 1,
>       "modified" : 1234567,
>       "updated" : 23454678
>     },{
>     "995398:fe6353e080d932cfc70cecd6e1f1b0e5" : {
>       "verified" : NO,
>       "currency" : "Exalted Orb",
>       "amount" : 1,
>       "modified" : 1234567,
>       "updated" : 23454678
>     }
>   }
> }
>
> Prior to executing the verification update, it should also check to see
> when the thread was last updated - if the thread was updated within the
> last *Time Period* (60s?) do not trigger an update
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/63>.
>



-- 
--
http://sites.google.com/site/thirdyderivera/

**Comment by trackpete** [comment]
Yes, when it's building, bumping a thread with verify will cause it to be tracked for future refresh updates.

I already focus refreshing threads only on the temp leagues, trying to get all threads in Standard would be basically impossible. ;)

**Comment by trackpete** [comment]
Won't need to do this anymore. :x
