### ISSUE TITLE
Rewrite clipboard text parsing

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#66]
The clipboard text processing subroutine should be rewritten, as it was failing in some circumstances.

It should include:

1. Determine item rarity > DONE
2. Determine item name > DONE
3. Determine item equiptype, itemtype, and baseitemtype > DONE
4. ~~ Note item requirements~~ > actually I don't care for price lookup
5. Note sockets > DONE
6. Build implicit mod hash
7. Build explicit mods hash
8. Build properties hash
9. Build attributes hash
10. Build pseudoMods hash

**Comment by trackpete** [comment]
[item clipboard examples.txt](https://github.com/trackpete/exiletools-indexer/files/73525/item.clipboard.examples.txt)


**NOTE: This all assumes US English, I haven't looked at any other format/data/etc! It's probable that we need to do internationalization support!**

The item data has no programmatic layout, so we have to make various assumptions. The following assumptions are generally believed to be true:

1. The first line contains Rarity in a `Rarity: rarity` pair
2. The second line contains the first part of the name. Sometimes a third line contains the rest.
3. The rarity and name are separated from the rest by `--------`
4. The first section enclosed in dashes will be properties for armor/weapons/gems/maps/talismans. This will include things like `Two Handed Axe`

The following section(s) are enclosed in dashes and always have an identifier to start with, and include the following matchable regexps:

1. `Requirements:`
  * `Level: (\d+)`
  * `Str: (\d+)`
  * `Int: (\d+)`
  * `Dex: (\d+)`

The following strings can be extracted via regexp across the entire text:

* `Quality: +(\d+)%`
* `Armour: (\d+)`
* `Evasion Rating: (\d+)`
* `Energy Shield: (\d+)`
* `Sockets: (.*?)`
* `Item Level: (\d+)`
* `Physical Damage: (\d+)-(\d+)`
* `Critical Strike Chance: (\d+(\.\d{0,2})?)%`
* `Attacks per Second: (\d+(\.\d{0,2})?)`
* `Talisman Tier: (\d+)`
* `Map Tier: (\d+)`
* `Stack Size: (\d+)\/(\d+)`

Elemental Damage is NOT designated and must be multi regexp'd - it may be better to pull this directly from mods. For example:

`Elemental Damage: 30-53 (augmented), 8-140 (augmented)`

**Comment by trackpete** [comment]
Additionally, we can determine item attributes by searching for the following lines all on their own:

* `unidentified`
* `corrupted`

**Comment by trackpete** [comment]
On identifying base item types:

**Maps:**

* Can be identified by looking for the `Map Tier` property

**Divination Cards:**

* Divination cards are Normal items with a Stack Size
* I don't think other things can have stack size

**Flasks:**

* Search for `Right click to drink`

**Jewels:**

* Name should contain `Jewel` with word boundaries and not be any other item type

**Talisman:**

* Name should contain `Talisman` with word boundaries and not be any other item type

**Gem:**

* Will be `Rarity: Gem`

**Currency:**

* Will be `Rarity: Currency`

All other item types must be determined by the item's name using a lookup against known item type names.

**Comment by Xebtria** [comment]
any chances that this is seeing some love in the future? I'd love to see that price check macro working again :/

**Comment by trackpete** [comment]
I'm closing this issue and opening a new one - working on updating this service using node.js.
