### ISSUE TITLE
Ladder Analysis: Top Player Skilltrees

### ISSUE THREAD

**Issue by trackpete** [trackpete/exiletools-indexer#90]
This will be a new primary feature - it is not tied directly to the Shop Forum Indexer, but I'm including it in this project because it will use the same underlying infrastructure and can optionally be enabled by anyone running the indexer.

# Outline
On a nightly basis, fetch and analyze the character skilltree data of all characters on the ladder. Store this information in an ElasticSearch index.

# Specs - Character Indexer
* Runs Nightly

1. Use the [ExileTools Ladder API](http://api.exiletools.com/info/ladder.php) to generate a full list of characters on the ladder for a league - [example for Standard](http://api.exiletools.com/ladder?league=standard&showAll=1)
2. For each character, check the [official character API](http://api.exiletools.com/info/official-passives.html) for their skilltree. [example for rank 1252 in Standard at time of writing](https://www.pathofexile.com/character-window/get-passive-skills?accountName=PriReis&character=PompalaNecla&reqData=0)
3. Analyze the skill tree by comparing node id's to a default table. Insert the raw skill tree data into ElasticSearch, as well as analyzed Summary Data. Analyzed Summary Data should include the total and count of all nodes with the same name (i.e. `"+10 to Intelligence":10, "Total + to Intelligence":100`). It should also include specifics on keystones, which I believe can be detected simply by looking for `Keystone` in the icon URL.
4. Data should be inserted into ElasticSearch with an id of rank+date. Date should be tracked in the ES data as well.

**Comment by trackpete** [comment]
Note: In order to aggregate search for things like the most common nodes, the JSON data will need to be stored as [Nested Objects](https://www.elastic.co/guide/en/elasticsearch/guide/current/nested-objects.html).

See the [comments in this GitHub thread for examples](https://github.com/elastic/elasticsearch/issues/5789).

**Comment by trackpete** [comment]
Analyzing the skill tree data for jewels:

All jewel slots are included in all skilltrees regardless of `reqData` - this is an object called `jewel_slots` which contains an array of objects. Each object in the array includes an `id` and another object that contains the `id` again, the `name` (always Jewel Socket), and the `hash` which indicates the point on the tree where this slot lives.

Jewels are included under an `items` section in the skilltree JSON data. It shows the entire jewel itself in normal item JSON. The `frameType` section now includes additional parameters above just the item type - these are `x` and `y` values and don't seem to be in part of the JSON structure. The `x` value appears to indicate the point in the jewel_slot array where the item exists.

So, to find how many jewel slots the skill tree has:

1. Iterate `jewel_slots` and note all of the hashes
2. Iterate the `hashes` data and note any hash that matches the jewel slot hashes

To determine where the jewels are placed in the tree:

1. Look at the `x` value under `frameType` and compare this to the `jewel_slots` array - an `x` value of `2` indicates the jewel is in the third slot in the array.

**Comment by trackpete** [comment]
I've created an initial program under `ladder-skilltrees` called `get-ladder-skilltrees.pl` which will pull from the Ladder API and then get the skilltrees for every character and put them into Elastic Search, using Nested Objects for the nodes so aggregate searches will work.

Next up, I need to write a program to fetch the basic skilltree data and create a lookup table for each node hash so that we can index exactly what they are.

In my initial analysis, it looks like the `Retribution` node is the most common, with 233 players using it! WOO. IT'S ALIVE.

**Comment by trackpete** [comment]
I've started work on parsing the base skilltree data to create a lookup table for node information. It's not immediately clear what all of these attributes are.

The node data is an array of objects under `nodes`. I've identified the following important values:

* `id` = the id # of the node
* `icon` = the trailing icon URL (need to fix regexp escapes and add prefix - https://p7p4m6s5.ssl.hwcdn.net/image)
* `dn` = the node name
* `sd` = an array of the mods for the node
* `g` = I think this is just an incrementing number for the place in the array?
* `out` = shows the node id's that are connected to it
* `not` = if set to `true` this seems to indicate it's a Noteable node (bigger than normal, not keystone)
* `ks` = if set to `true` this is a Keystone node
* `ia` = adds # intelligence
* `sa` = adds # strength
* `da` = adds # dex
* `m` = Mastery node. These nodes don't have statistics/mods under `sd` - wtf? Wait, there are equivalent ones. Maybe these are dead nodes? Yeah I think they are obselete.

I'm not sure what everything else is.

**Comment by trackpete** [comment]
I think this is done for now!

http://exiletools.com/blog/2016/02/02/analyzing-skilltree-data-for-the-top-path-of-exile-players/

I'll work on gathering full stats into a post to share all the data tomorrow.

**Comment by EmmittJ** [comment]
Just to complete you understanding of what each variable is when looking at nodes, I will give you a list:
`a` = angle, this is used to calculate where it needs to go on the orbit
`sd` = attributes 
`g` = I have zero idea. This is the only thing I haven't figured out 
`icon` = icon path
`id` = node id
`ks` = Is keystone (True/False)
`not` = Is Notable (True/False)
`m` = Is Mastery (True/False) note: these are the images that appear in some of the node circles 
`out` = linked nodes 
`dn` = node name
`o` = How many orbits a cluster of nodes has
`oidx` = the index of where the node is at in a cluster
`spc` = class starting node (character portraits)
`da` = adds dex 
`ia` = adds int
`sa` = adds str

**Comment by trackpete** [comment]
That's awesome, thank you!

**Comment by EmmittJ** [comment]
Alright, from one of the web developers at GGG: the g is the ID of the group the nodes belong to.
