### ISSUE TITLE
Add item base attribute (Crude Bow, Astral Plate etc.)

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#96]
Currently we only have the ff:

 * attributes.baseItemType - armour, currency, weapon etc
 * attributes.itemType - boots, gloves, claw, wand etc

However the "base type" as in Rustic Sash or Crude Bow is not available.

**Comment by trackpete** [comment]
Agreed. I also need to update the hash to make sure I'm catching everything (I saw some notes that a new Demigod's Golden Obi or something wasn't being detected).

I will probably classify this as `attributes.itemBaseName`

**Comment by trackpete** [comment]
This has been added in v3 as `attributes.baseItemName`:

1. If the item is matched against a known gear base type, this attribute will be set to the match (i.e. "Saintly Chainmail"
2. If the item is not matched against a known gear base type, this attribute will be set to the original JSON `typeLine` attribute (this applies to things like Gems, Currency, etc. which are not in the gearBase hash)

Additionally, I've added the known map types to the gearBase hash and included the script that creates/updates the gearBase hash from poedb.tw into the `tools` subdirectory.

Note that these changes will not apply to the current production index yet and will not be pushed to GitHub until the official new API is announced.

**Comment by thirdy** [comment]
Just wanted to share,

For durian using poe.trade, on parsing the html, I had to check the item
title and match against this list of known base types:

https://github.com/thirdy/durian/blob/master/durian/script/basetypes.js

This improvement is one good step to eliminate this need

On Sat, Feb 27, 2016 at 3:36 AM, Pete Waterman <notifications@github.com>
wrote:

> Closed #96 <https://github.com/trackpete/exiletools-indexer/issues/96>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trackpete/exiletools-indexer/issues/96#event-568072261>
> .
>



-- 
--
http://sites.google.com/site/thirdyderivera/
