### ISSUE TITLE
Using JQuery and Angular to query exiletools?

### ISSUE THREAD

**Issue by thirdy** [trackpete/exiletools-indexer#97]
I'm no web-dev, but fortunately I got JQuery + exiletools working:

http://thirdy.github.io/helloexiletools.html

However, the dataType tripped me here:

`dataType: 'text', // if this is 'text jsonp', success is not called, why?`

Just curious, what's special about jsonp? Note that this was based on the sample given in the [indexer doc](http://api.exiletools.com/info/indexer.html).

Another question I have is, does the ES js client work against exiletools? They seem to be not using the REST API but runs as a 'client'?

I got this es + angular, but it's not working:

http://thirdy.github.io/helloexiletoolsangular.html

Github sources:
https://github.com/thirdy/thirdy.github.io/blob/master/helloexiletools.html
https://github.com/thirdy/thirdy.github.io/blob/master/helloexiletoolsangular.html

Would appreciate any help I can get :D

**Comment by trackpete** [comment]
Just heading to sleep now and will reply more later, but if you check the
www directory in the indexer project there are working examples.

**Comment by thirdy** [comment]
Thanks, saw this one, looks promising to try later:

```
EsConnector.service('es', function (esFactory) {
  return esFactory({ host: 'http://apikey:<your api key>@api.exiletools.com' });
});
```

**Comment by trackpete** [comment]
The API limits access to specific end-points and will not allow access to the cluster API. The specific endpoints that are allowed can be seen here:

http://api.exiletools.com/info/indexer.html

Additionally, you will need to set `index` somewhere so it knows to go to `index` - because that request is going to `api.exiletools.com/_cluster` instead of `api.exiletools.com/index/_cluster` it's not even going to the same server that is hosting the API, hence the cors error. ;)

You need to add `  index: 'index',` to the es.search function.

**Comment by trackpete** [comment]
I've added a super simple hello world example using Angular. You can see this here:

http://exiletools.com/dashboard-dev/helloworld.html

HTML File:
```
<!doctype html>
<html lang="en" ng-app="EsConnector">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Hello World Example w/ Angular</title>

  <script src="https://code.jquery.com/jquery-2.2.1.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.5.0/angular.min.js"></script>
  <!-- Warning, I've seen some glitchy errors on newer versions, I think they require node.js installation or some idiocy -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/elasticsearch/10.0.1/elasticsearch.angular.min.js"></script>
  <script src="js/es-helloworld.js"></script> --

</head>
<body>
<!-- Main div starts at 0 spacing for simplicity -->
<div id="main" style="width:100%;padding-left:50px;padding-right:50px" ng-controller="ExileToolsHelloWorld" >
  <h1>This is a hello world test. You should see response data below. If not, check your console!</h1>
  <hr width=100% size=1>

  <div>
    <li>Request took {{Response.took}} ms
    <li>Request matched {{Response.hits.total}} hits
    <p>Here is some information on the items returned:</p>
    
    <ul>
      <li ng-repeat="item in Response.hits.hits">{{item._source.info.fullName}},{{item._source.shop.updated}}</li>
    </ul>
  </div>
</div>
</body>
</html>
```

`es.js` file:
```
// We define an EsConnector module that depends on the elasticsearch module.     
var EsConnector = angular.module('EsConnector', ['elasticsearch']);

// Create the es service from the esFactory
EsConnector.service('es', function (esFactory) {
  return esFactory({ host: 'http://apikey:DEVELOPMENT-Indexer@api.exiletools.com' });
});

EsConnector.controller('ExileToolsHelloWorld', function($scope, es) {
  // Set up the ES Search function
  es.search({
  index: 'index',
  // Query for the 100 most recently updated items of items updated in the last day
  body: {
    "sort": [
      {
        "shop.updated": {
          "order": "desc"
        }
      }
    ], 
    "query": {
      "filtered": {
        "filter": {
          "range": {
            "shop.updated": {
              "gte": "now-1d"
            }
          }
        }
      }
    },
    size:100
  }
  }).then(function (response) {
    $scope.Response = response;
  }, function (err) {
    console.trace(err.message);
  });

});
```

Super simple and clean. This will be included in the project when I push v3.

**Comment by thirdy** [comment]
example looks good! thanks

**Comment by eps1lon** [comment]
Theres also a es api for jQuery available under https://cdnjs.com/libraries/elasticsearch

So you dont have to manually call $.ajax and parse the response.
